### PR TITLE
:arrow_up: update @polkadot/packages

### LINKED ISSUE #32: Update polkadot apps lib
Hello,

currently paraspell has really old dependencies and it creates a big problem for dApps onboarding this sdk

```
➜  nft-gallery git:(main) ✗ pnpm why @polkadot/util@10.4.2
Legend: production dependency, optional only, dev only

dependencies:
@paraspell/sdk 0.0.25
├─┬ @polkadot/api 9.14.2
│ ├─┬ @polkadot/api-augment 9.14.2
│ │ ├─┬ @polkadot/api-base 9.14.2
│ │ │ ├─┬ @polkadot/rpc-core 9.14.2
│ │ │ │ ├─┬ @polkadot/rpc-augment 9.14.2
│ │ │ │ │ ├─┬ @polkadot/types 9.14.2
│ │ │ │ │ │ ├─┬ @polkadot/keyring 10.4.2
│ │ │ │ │ │ │ ├── @polkadot/util 10.4.2
│ │ │ │ │ │ │ └─┬ @polkadot/util-crypto 10.4.2
│ │ │ │ │ │ │   ├─┬ @polkadot/networks 10.4.2
```

Please update this repo to at least `10.2.2` thanks!

### PR DESCRIPTION
**Pull request by vikiival**
Close #32

### CODE REVIEW

**Comment by vikiival** [comment]
cc @michaeldev5

**Comment by dudo50** [comment]
@vikiival  newest version of Polkadot apps config has some issues at the moment. We have to manually update many node endpoints for our scripts because of that. Issue is due to friday to be resolved. I will notify you then. Thanks for understand.

**Comment by dudo50** [comment]
Yes, will do that today. Apps will be updated on friday.
With kind regards,
Team ParaSpell

**Comment by vikiival** [comment]
berry Small

**Pull request merged**
